# Generated by Django 5.0.4 on 2025-04-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('accomplished', models.BooleanField(default=False)),
            ],
        ),
    ]
