# Generated by Django 5.0.4 on 2025-04-28 07:33

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gt', django.db.models.functions.datetime.Now())), name='valid_due_date', violation_error_message="Due Date Can't Be In The Past."),
        ),
    ]
