# Generated by Django 5.0.4 on 2025-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_created_at_agenda_valid_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
