# Generated by Django 5.0.4 on 2025-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
