# Generated by Django 5.0.4 on 2025-04-28 08:15

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_agenda_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agenda',
            name='valid_due_date',
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gt', agenda.models.CurrentDate())), name='valid_due_date', violation_error_message='Due Date Must Be After Creation Date.'),
        ),
    ]
