# Generated by Django 5.0.4 on 2025-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_agenda_valid_due_date_agenda_valid_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('pink', 'Pink')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('bd', 'Birthday'), ('holiday', 'Holiday')], max_length=20),
        ),
    ]
