# Generated by Django 6.0.3 on 2026-03-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('publish_document', 'Can publish document'), ('archive_document', 'Can archive document'), ('share_document', 'Can share document')]},
        ),
    ]
