# Generated by Django 5.0.4 on 2025-05-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_restaurant_options_alter_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='restaurants',
        ),
    ]
