# Generated by Django 5.0.4 on 2025-05-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_staffrestaurant_staff_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffrestaurant',
            old_name='joined_at',
            new_name='date_joined',
        ),
    ]
