# Generated by Django 5.0.4 on 2026-01-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
