# Generated by Django 5.0.4 on 2026-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_restaurant_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
