# Generated by Django 6.0.1 on 2026-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_alter_sale_options_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='latitude_constraint', violation_error_message='Latitude needs to be in the range [-90, 90]'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='longitude_constraint', violation_error_message='Longitude needs to be in the range [-180, 180]'),
        ),
    ]
