# Generated by Django 6.0.1 on 2026-02-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_restaurant_latitude_constraint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('name', 'website'), name='name_website_unique', violation_error_message="Name and website can't match with another restaurant"),
        ),
    ]
