# Generated by Django 5.0.4 on 2026-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_restaurant_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nick_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
