# Generated by Django 5.0.4 on 2025-03-05 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=90)),
                ('phone_number', models.CharField(max_length=15)),
                ('categories', models.JSONField()),
                ('profit', models.FloatField(max_length=4)),
                ('contract', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Computer', 'Computer'), ('Telephone', 'Telephone'), ('Earphone', 'Earphone')], max_length=20)),
                ('available_colors', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('used', models.BooleanField(default=False)),
                ('promotion_date_ends', models.DateField(error_messages={'past': "End date can't be in the past"})),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.seller')),
            ],
        ),
    ]
