# Generated by Django 5.0.4 on 2025-03-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rating_valid_rating_cons'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='valid_latitude', violation_error_message='Latitude must be in the range -90 and 90'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -180), ('latitude__lte', 180)), name='valid_longitude', violation_error_message='Longitude must be in the range -180 and 180'),
        ),
    ]
