# Generated by Django 5.0.4 on 2025-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_valid_latitude_restaurant_valid_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_opened',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
