# Generated by Django 5.0.4 on 2025-03-19 07:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_date_opened_alter_restaurant_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name_cons'),
        ),
    ]
