# Generated by Django 5.0.4 on 2025-03-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurant_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restaurant',
            name='unique_name_cons',
        ),
    ]
