# Generated by Django 5.0.4 on 2025-03-19 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_restaurant_name_restaurant_unique_name_cons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='user_resto_uniq_cons'),
        ),
    ]
