# Generated by Django 5.0.4 on 2025-03-11 18:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(choices=[('computer', 'Computer'), ('phone', 'Phone'), ('earphone', 'Earphone'), ('smartwatch', 'Smartwatch')], max_length=200)),
                ('product_price', models.PositiveIntegerField()),
                ('warrant_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('is_used', models.BooleanField(default=False)),
                ('promotion_ends_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
