# Generated by Django 5.0.4 on 2025-03-13 16:08

import datetime
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion_ends_date',
            field=models.DateField(default=datetime.date.today, validators=[store.models.validate_promotion_date]),
        ),
    ]
