# Generated by Django 6.0.1 on 2026-02-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='user',
            new_name='users',
        ),
    ]
