# Generated by Django 6.0.1 on 2026-02-24 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_receiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='privateroom',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='room_user_unique', violation_error_message='Room and User must be unique'),
        ),
    ]
