# Generated by Django 6.0.1 on 2026-02-27 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_privateroom_room_user_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('delivered', 'Delivered'), ('sent', 'Sent')], default='sent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='privateroom',
            index=models.Index(fields=['room'], name='chat_privat_room_id_ff772c_idx'),
        ),
        migrations.AddIndex(
            model_name='privateroom',
            index=models.Index(fields=['user'], name='chat_privat_user_id_eac443_idx'),
        ),
    ]
