# Generated by Django 6.0.1 on 2026-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
