# Generated by Django 6.0.1 on 2026-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_posted', 'name']},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'seller'), name='name_seller_unqiue', violation_error_message='Name and Seller need to be unique at once'),
        ),
    ]
