# Generated by Django 6.0.1 on 2026-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_seller_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'female')], default=''),
        ),
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.CheckConstraint(condition=models.Q(('phone__startswith', '+250')), name='phone_starts_with_+250'),
        ),
    ]
