# Generated by Django 6.0.1 on 2026-02-07 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_buyer_order_remove_seller_phone_starts_with__250_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBackUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('appliance', 'Appliance'), ('beauty', 'Beauty'), ('clothing', 'Clothing'), ('travel', 'Travel')], max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('date_posted', models.DateField()),
                ('date_backedup', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'date_posted', 'ordering': ['-date_posted', 'name']},
        ),
    ]
