# Generated by Django 5.0.4 on 2025-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
