# Generated by Django 6.0.1 on 2026-02-07 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_seller_gender_seller_phone_starts_with__250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('cost_price', models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='seller',
            name='phone_starts_with_+250',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.CheckConstraint(condition=models.Q(('phone__startswith', '+250')), name='seller_phone_starts_with_+250'),
        ),
        migrations.AddConstraint(
            model_name='buyer',
            constraint=models.CheckConstraint(condition=models.Q(('phone__startswith', '+250')), name='buyer_phone_starts_with_+250'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product'),
        ),
    ]
