# Generated by Django 5.0.4 on 2026-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restaurant_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
