# Generated by Django 6.0.1 on 2026-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_seller_gender_seller_slug_alter_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
