# Generated by Django 5.0.4 on 2025-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
