# Generated by Django 6.0.1 on 2026-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='gender',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
