# Generated by Django 5.0.4 on 2025-03-27 11:42

import datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=90, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('permissions', models.JSONField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_name_cons'),
        ),
    ]
