# Generated by Django 5.0.4 on 2025-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
