# Generated by Django 5.0.4 on 2025-03-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=90, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('categories', models.JSONField()),
                ('profit', models.FloatField(max_length=4)),
                ('contract', models.CharField(max_length=30)),
            ],
        ),
    ]
